--
-- PostgreSQL database dump
--

\restrict p26dY9ZM7KoQEkAfYI5HIj3VpTuXcAv9Z5LjhUWfnKY9PwfecebAp0CmgWN4pqc

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO admin;

--
-- Name: inventory_accessory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.inventory_accessory (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    model character varying(50),
    acquisition_date date,
    price numeric(10,2),
    status character varying(10) NOT NULL,
    description text,
    region character varying(20),
    platform character varying(20),
    complete boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    store character varying(20) NOT NULL,
    protective character varying(20) NOT NULL
);


ALTER TABLE public.inventory_accessory OWNER TO admin;

--
-- Name: inventory_accessory_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.inventory_accessory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_accessory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_accessory_missing_components; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.inventory_accessory_missing_components (
    id bigint NOT NULL,
    accessory_id bigint NOT NULL,
    missingcomponent_id bigint NOT NULL
);


ALTER TABLE public.inventory_accessory_missing_components OWNER TO admin;

--
-- Name: inventory_accessory_missing_components_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.inventory_accessory_missing_components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_accessory_missing_components_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_console; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.inventory_console (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    model character varying(50),
    acquisition_date date,
    price numeric(10,2),
    status character varying(10) NOT NULL,
    description text,
    region character varying(20),
    platform character varying(20),
    complete boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    edition character varying(100) NOT NULL,
    store character varying(20) NOT NULL,
    protective character varying(20) NOT NULL
);


ALTER TABLE public.inventory_console OWNER TO admin;

--
-- Name: inventory_console_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.inventory_console ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_console_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_console_missing_components; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.inventory_console_missing_components (
    id bigint NOT NULL,
    console_id bigint NOT NULL,
    missingcomponent_id bigint NOT NULL
);


ALTER TABLE public.inventory_console_missing_components OWNER TO admin;

--
-- Name: inventory_console_missing_components_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.inventory_console_missing_components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_console_missing_components_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_game; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.inventory_game (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    model character varying(50),
    acquisition_date date,
    price numeric(10,2),
    status character varying(10) NOT NULL,
    description text,
    region character varying(20),
    platform character varying(20),
    complete boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    edition character varying(100) NOT NULL,
    store character varying(20) NOT NULL,
    protective character varying(20) NOT NULL
);


ALTER TABLE public.inventory_game OWNER TO admin;

--
-- Name: inventory_game_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.inventory_game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_game_missing_components; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.inventory_game_missing_components (
    id bigint NOT NULL,
    game_id bigint NOT NULL,
    missingcomponent_id bigint NOT NULL
);


ALTER TABLE public.inventory_game_missing_components OWNER TO admin;

--
-- Name: inventory_game_missing_components_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.inventory_game_missing_components ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_game_missing_components_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_itemimage; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.inventory_itemimage (
    id bigint NOT NULL,
    object_id integer NOT NULL,
    image character varying(255) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    content_type_id integer NOT NULL,
    CONSTRAINT inventory_itemimage_object_id_check CHECK ((object_id >= 0))
);


ALTER TABLE public.inventory_itemimage OWNER TO admin;

--
-- Name: inventory_itemimage_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.inventory_itemimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_itemimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_missingcomponent; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.inventory_missingcomponent (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.inventory_missingcomponent OWNER TO admin;

--
-- Name: inventory_missingcomponent_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.inventory_missingcomponent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_missingcomponent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL
);


ALTER TABLE public.user_user OWNER TO admin;

--
-- Name: user_user_groups; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_user_groups OWNER TO admin;

--
-- Name: user_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_user_user_permissions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_user_user_permissions OWNER TO admin;

--
-- Name: user_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add missing component	11	add_missingcomponent
26	Can change missing component	11	change_missingcomponent
27	Can delete missing component	11	delete_missingcomponent
28	Can view missing component	11	view_missingcomponent
29	Can add Imagen	10	add_itemimage
30	Can change Imagen	10	change_itemimage
31	Can delete Imagen	10	delete_itemimage
32	Can view Imagen	10	view_itemimage
33	Can add game	9	add_game
34	Can change game	9	change_game
35	Can delete game	9	delete_game
36	Can view game	9	view_game
37	Can add console	8	add_console
38	Can change console	8	change_console
39	Can delete console	8	delete_console
40	Can view console	8	view_console
41	Can add accessory	7	add_accessory
42	Can change accessory	7	change_accessory
43	Can delete accessory	7	delete_accessory
44	Can view accessory	7	view_accessory
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	user	user
7	inventory	accessory
8	inventory	console
9	inventory	game
10	inventory	itemimage
11	inventory	missingcomponent
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-14 17:22:34.358993+00
2	contenttypes	0002_remove_content_type_name	2026-08-14 17:22:34.363278+00
3	auth	0001_initial	2026-08-14 17:22:34.389157+00
4	auth	0002_alter_permission_name_max_length	2026-08-14 17:22:34.392651+00
5	auth	0003_alter_user_email_max_length	2026-08-14 17:22:34.396502+00
6	auth	0004_alter_user_username_opts	2026-08-14 17:22:34.399622+00
7	auth	0005_alter_user_last_login_null	2026-08-14 17:22:34.402583+00
8	auth	0006_require_contenttypes_0002	2026-08-14 17:22:34.403751+00
9	auth	0007_alter_validators_add_error_messages	2026-08-14 17:22:34.406488+00
10	auth	0008_alter_user_username_max_length	2026-08-14 17:22:34.40977+00
11	auth	0009_alter_user_last_name_max_length	2026-08-14 17:22:34.41262+00
12	auth	0010_alter_group_name_max_length	2026-08-14 17:22:34.416086+00
13	auth	0011_update_proxy_permissions	2026-08-14 17:22:34.418611+00
14	auth	0012_alter_user_first_name_max_length	2026-08-14 17:22:34.421155+00
15	user	0001_initial	2026-08-14 17:22:34.447199+00
16	admin	0001_initial	2026-08-14 17:22:34.459536+00
17	admin	0002_logentry_remove_auto_add	2026-08-14 17:22:34.463489+00
18	admin	0003_logentry_add_action_flag_choices	2026-08-14 17:22:34.467512+00
19	inventory	0001_initial	2026-08-14 17:22:34.518202+00
20	inventory	0002_game_edition	2026-08-14 17:22:34.523324+00
21	inventory	0003_alter_itemimage_image	2026-08-14 17:22:34.525876+00
22	inventory	0004_alter_itemimage_image	2026-08-14 17:22:34.528808+00
23	inventory	0005_console_edition	2026-08-14 17:22:34.533274+00
24	sessions	0001_initial	2026-08-14 17:22:34.541921+00
25	inventory	0006_accessory_store_console_store_game_store	2026-09-29 15:16:40.221264+00
26	inventory	0007_alter_accessory_store_alter_console_store_and_more	2026-09-29 15:21:52.805244+00
27	inventory	0008_alter_accessory_store_alter_console_store_and_more	2026-09-29 15:22:27.540624+00
28	inventory	0009_alter_accessory_store_alter_console_store_and_more	2026-09-29 15:22:59.57393+00
29	inventory	0010_alter_accessory_store_alter_console_store_and_more	2026-09-29 15:23:13.555588+00
30	inventory	0011_alter_accessory_store_alter_console_store_and_more	2026-09-29 15:23:36.580971+00
31	inventory	0012_accessory_protective_console_protective_and_more	2026-09-29 15:28:43.797203+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
mrdafmio8pw8qeyp6450oxpfvnwcwbap	.eJxVjL0KwzAQg9_FczGO_69j9zyDOfucOm1xIE6m0ndvDBlaBBr0SXqzgPtWwt7yGmZiVzawy28WMT1z7YAeWO8LT0vd1jnyXuEnbXxcKL9uZ_fvoGArfU3ReYg4kbTWCAPKJS0HhREmIEha6GSkB3D2MJ89HlIehCDIUkX2-QLcXTdG:1wfgll:ln3-TUuZPuHNzCnDUhJomkzQiJoRLFKBNYM0a1Gm2EY	2026-07-17 16:29:37.193257+00
de49qpmnzwt57ekqhyqcob30dm225dry	.eJxVjEEOwiAQRe_C2hCGUgou3XsGMgyDVA0kpV0Z765NutDtf-_9lwi4rSVsnZcwJ3EWIE6_W0R6cN1BumO9NUmtrssc5a7Ig3Z5bYmfl8P9OyjYy7ceHDG4RASK0RAYzJn05NFjzGDSgN7GzDENYJwZLWvrJ-NV1ug0jUq8PwvsOF4:1wdc3v:IahOexhUp2wLqYMvKVyXqEsuLrckCKAjb75pK-iszio	2026-07-11 23:03:47.222+00
cw9co5dfffmjow3fotlq1p0xyco2isin	.eJxVjL0KwzAQg9_FczGO_69j9zyDOfucOm1xIE6m0ndvDBlaBBr0SXqzgPtWwt7yGmZiVzawy28WMT1z7YAeWO8LT0vd1jnyXuEnbXxcKL9uZ_fvoGArfU3ReYg4kbTWCAPKJS0HhREmIEha6GSkB3D2MJ89HlIehCDIUkX2-QLcXTdG:1xBZSh:0EVffMd4ExES923Ud6ayeUdGSYw-GEhxO25aDRStQi4	2026-10-13 15:09:43.428426+00
\.


--
-- Data for Name: inventory_accessory; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.inventory_accessory (id, name, model, acquisition_date, price, status, description, region, platform, complete, created_at, updated_at, store, protective) FROM stdin;
1	Game Link Cable: Game Boy Advance	\N	2025-12-29	41.35	GOOD	\N	PAL ESPAÑA	GBA	f	2026-06-29 11:42:07.729+00	2026-06-29 11:42:27.584+00	Wallapop	Sin funda
2	PlayMania Guia Grand Theft Auto: San Andreas	\N	2025-06-17	12.28	GOOD	\N	PAL ESPAÑA	PS2	t	2026-06-30 19:01:29.433+00	2026-06-30 19:01:30.752+00	Wallapop	Sin funda
3	Mando DualSense	\N	2022-11-08	45.81	GOOD	\N	PAL ESPAÑA	PS5	t	2026-06-30 20:30:31.513+00	2026-06-30 20:30:44.694+00	Wallapop	Sin funda
4	Mando DualShock 4	\N	2025-05-08	21.48	MINT	Mando comprado para completar la consola PlayStation 4	PAL ESPAÑA	PS4	t	2026-06-30 20:34:19.076+00	2026-06-30 20:39:30.163+00	Wallapop	Sin funda
5	Auricular	\N	2025-03-18	8.18	MINT	Auricular original para completar la consola PlayStation 4 Slim	PAL ESPAÑA	PS4	t	2026-06-30 20:35:47.852+00	2026-06-30 20:36:18.501+00	Wallapop	Sin funda
6	Demo Winter Releases '98	\N	2024-04-04	15.64	GOOD	\N	PAL ESPAÑA	PS1	t	2026-07-03 16:13:24.599+00	2026-07-03 16:13:37.992+00	Wallapop	Sin funda
\.


--
-- Data for Name: inventory_accessory_missing_components; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.inventory_accessory_missing_components (id, accessory_id, missingcomponent_id) FROM stdin;
\.


--
-- Data for Name: inventory_console; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.inventory_console (id, name, model, acquisition_date, price, status, description, region, platform, complete, created_at, updated_at, edition, store, protective) FROM stdin;
12	PlayStation 5 FAT	CFI-1116A	2022-09-01	\N	MINT	Consola conseguida en un sorteo sorteado por Gemita.	PAL ESPAÑA	PS5	t	2026-06-30 18:51:40.971+00	2026-06-30 18:51:43.118+00	Normal	Wallapop	Sin funda
13	Game Boy	GM5935623	2024-12-17	63.30	GOOD	Regalo de mi padre.	PAL ESPAÑA	GB	f	2026-06-30 18:55:55.773+00	2026-06-30 18:56:24.332+00	Nornal	Wallapop	Sin funda
1	PlayStation 1 FAT	SCPH-9002 C	2025-02-04	71.39	GOOD	PlayStation 1 FAT, manuales y demo comprados apartes.	PAL ESPAÑA	PS1	f	2026-06-27 23:12:24.069+00	2026-06-30 16:39:04.554+00	Normal	Wallapop	Sin funda
2	PSOne	SCPH-102 C	2026-04-20	49.41	GOOD	La PSOne tenia una pegatina de envió,.	PAL ESPAÑA	PS1	f	2026-06-30 16:12:26.051+00	2026-06-30 16:39:17.48+00	Normal	Wallapop	Sin funda
3	PlayStation 2 Slim	SCPH-70004 SS	2025-01-09	52.61	MINT	Manuales de la consola comprados aparte, consola 37,43 € y manuales 15,18 €	PAL ESPAÑA	PS2	t	2026-06-30 16:17:59.822+00	2026-06-30 16:35:15.778+00	Satin Silver	Wallapop	Sin funda
4	PlayStation 2 SuperSlim	SCPH-90004	2026-06-15	110.49	GOOD	Me costo ese precio pero a la espera de vender la consola, ya que la consola ya la tenia yo.	PAL ESPAÑA	PS2	f	2026-06-30 16:22:57.574+00	2026-06-30 16:34:39.297+00	Bundle Disney SingStar	Wallapop	Sin funda
5	PlayStation 2 Slim	SCPH-70004	2004-12-24	\N	FAIR	Esta PS2 Slim es la que me compraron en la época cuando salió, así que no me costo nada.	PAL ESPAÑA	PS2	f	2026-06-30 17:27:49.248+00	2026-06-30 17:30:04.51+00	Normal	Wallapop	Sin funda
6	PlayStation 3 FAT	CECHK04	2026-03-24	61.67	FAIR	Esta consola le compre el insert (cartones)  que envuelven la consola.	PAL ESPAÑA	PS3	f	2026-06-30 17:34:54.672+00	2026-06-30 17:42:13.774+00	Bundle LittleBigPlanet	Wallapop	Sin funda
7	PlayStation 3: SuperSlim	CECH-4004A	2024-03-01	72.68	GOOD	Esta consola tiene un insert hecho por mi de cartón.	PAL ESPAÑA	PS3	f	2026-06-30 17:48:14.128+00	2026-06-30 17:49:19.094+00	Normal	Wallapop	Sin funda
8	PlayStation 4 Slim	CUH-2016A	2017-09-19	269.99	FAIR	Consola comprada nueva.	PAL ESPAÑA	PS4	t	2026-06-30 17:57:01.147+00	2026-06-30 18:03:36.445+00	bundle Minecraft	Wallapop	Sin funda
9	PSP Slim	PSP-2004 PB	2025-09-12	101.13	MINT	Esta completa pero solo el falta el plástico que envolvía a la consola	PAL ESPAÑA	PSP	t	2026-06-30 18:10:12.148+00	2026-06-30 18:12:42.227+00	Bundle Clank Agente Secreto	Wallapop	Sin funda
10	New Nintendo 3DS XL	RED-S-BAAA(EUB)	2024-08-21	188.94	GOOD	Tanto caja como tarjetas RA se compraron aparte, falta algún manual (creo)	PAL ESPAÑA	3DS	f	2026-06-30 18:17:50.243+00	2026-06-30 18:18:44.482+00	Azul  Metáloco	Wallapop	Sin funda
11	Game Boy Advance	AC13905443	2025-12-26	58.13	GOOD	El precio se debe a que la consola ya la tenia, el precio es por la caja de la consola (manuales, folletos, ..etc) y Caja de Super Mario Advance 2.	PAL ESPAÑA	GBA	t	2026-06-30 18:24:49.123+00	2026-06-30 20:17:50.271+00	Glacier	Wallapop	Sin funda
\.


--
-- Data for Name: inventory_console_missing_components; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.inventory_console_missing_components (id, console_id, missingcomponent_id) FROM stdin;
\.


--
-- Data for Name: inventory_game; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.inventory_game (id, name, model, acquisition_date, price, status, description, region, platform, complete, created_at, updated_at, edition, store, protective) FROM stdin;
1	Metal Gear Solid	\N	2024-12-04	110.00	MINT	Metal Gear Solid PS1, caja cambiada  por el Final Fantasy VIII y el poster comprado a parte.	PAL ESPAÑA	PS1	t	2026-06-27 23:35:33.502+00	2026-06-29 12:26:16.58+00	Black Label	Wallapop	Sin funda
2	Final Fantasy VIII	\N	2024-01-22	41.80	GOOD	Final Fantasy VIII con  la caja no cierra bien	PAL ESPAÑA	PS1	t	2026-06-28 19:19:34.619+00	2026-06-29 12:25:50.083+00	Black Label	Wallapop	Sin funda
3	Mickey Wild Advanture	\N	2023-08-09	31.05	SEALED	Mickey Wild Advanture precintado, pero tiene dos trozos del precinto roto y dos rajas en la parte delantera de la caja.	PAL ESPAÑA	PS1	t	2026-06-28 19:22:07.493+00	2026-06-29 12:26:24.852+00	Platinum	Wallapop	Sin funda
4	Rayman	\N	2023-08-11	20.30	GOOD	Rayman viene de italia.	PAL ESPAÑA	PS1	t	2026-06-28 19:26:17.371+00	2026-06-29 12:26:30.683+00	Black Label	Wallapop	Sin funda
5	Rayman 2	\N	2026-06-20	27.15	GOOD	Rayman 2 comprado por vinted no me costo nada ya que vendí Rayman 2 Platinum.	PAL ESPAÑA	PS1	t	2026-06-28 19:31:00.88+00	2026-06-29 12:26:36.818+00	Black Label	Wallapop	Sin funda
6	Disney Atlantis: El Imperio Perdido	\N	2024-06-14	15.18	GOOD	Disney Atlantis: El Imperio Perdido,  caja cambiada ya que estaba rota.	PAL ESPAÑA	PS1	t	2026-06-28 19:34:14.159+00	2026-06-29 12:25:43.357+00	Black Label	Wallapop	Sin funda
7	Gran Turismo	\N	2023-08-11	10.94	GOOD	Gran Turismo viene desde Paises Bajos, tiene la caja rota.	PAL UK	PS1	t	2026-06-28 19:39:00.528+00	2026-06-29 12:25:56.309+00	Black Label	Wallapop	Sin funda
12	Fifa 2004	\N	2024-03-25	8.18	FAIR	Juego comprado con el disco de Tomb Raider II	PAL ESPAÑA	PS1	t	2026-06-30 19:05:00.202+00	2026-06-30 19:16:17.29+00	Black Label	Wallapop	Sin funda
29	Rayman 3: Hoodlum Havoc	\N	2026-02-11	11.40	MINT	\N	PAL ESPAÑA	PS2	t	2026-06-30 20:04:25.983+00	2026-06-30 20:04:27.218+00	Black Label	Wallapop	Sin funda
30	Peter Jackson's King Kong	\N	2025-08-13	18.28	SEALED	\N	PAL ESPAÑA	PS2	t	2026-06-30 20:06:15.838+00	2026-06-30 20:06:16.629+00	Black Label	Wallapop	Sin funda
31	Kinetic Combat + EYE TOY	\N	2025-08-13	17.28	SEALED	\N	PAL ESPAÑA	PS2	t	2026-06-30 20:08:07.59+00	2026-06-30 20:09:30.859+00	Pack EYE TOY	Wallapop	Sin funda
33	Golden Sun	\N	2026-05-22	67.65	GOOD	Falta el manual principal del juego y plástico que envuelve el cartucho.	PAL ESPAÑA	GBA	f	2026-06-30 20:14:03.261+00	2026-06-30 20:14:04.163+00	Normal	Wallapop	Sin funda
34	Super Mario Advance 2	\N	2025-12-26	21.93	GOOD	Falta manual de advertencia, el precio se debe a el manual principal del juego y el cartucho, ya que la caja me vino con la caja de la Game Boy Advance.	PAL ESPAÑA	GBA	f	2026-06-30 20:15:33.551+00	2026-06-30 20:20:29.464+00	Normal	Wallapop	Sin funda
35	Spider-man	\N	2025-03-25	36.43	GOOD	\N	PAL ESPAÑA	GBA	t	2026-06-30 20:21:31.885+00	2026-06-30 20:21:32.914+00	Normal	Wallapop	Sin funda
36	Pokemon Edicion Azul	\N	2024-12-19	31.05	FAIR	\N	PAL ESPAÑA	GB	f	2026-06-30 20:22:36.59+00	2026-06-30 20:22:37.421+00	Normal	Wallapop	Sin funda
37	Pokemon Edicion Plata	\N	2001-12-24	\N	FAIR	El juego es el que me compraron en la época cuando salió.	PAL ESPAÑA	GBC	f	2026-06-30 20:24:30.561+00	2026-06-30 20:25:15.52+00	Normal	Wallapop	Sin funda
38	Tetris	\N	2026-03-12	16.38	GOOD	\N	PAL ESPAÑA	GB	f	2026-06-30 20:26:31.567+00	2026-06-30 20:26:32.164+00	Normal	Wallapop	Sin funda
10	Crash Bandicoot 3: Warped	\N	2024-01-17	42.93	MINT	Este juego se compro en un lote de 2 juegos este y el tony hawk's, tambien tiene la demo del Winter Release '98.	PAL ESPAÑA	PS1	t	2026-06-29 11:39:32.392+00	2026-06-30 19:20:36.712+00	Black Label	Wallapop	Sin funda
11	Anna Kournikova's Smash Court Tennis	\N	2004-12-24	3.00	FAIR	Juego comprado en la época cuando salió, así que los 3 € son del manual que compre a posterior.	PAL ESPAÑA	PS1	t	2026-06-29 12:14:40.567+00	2026-06-29 12:25:24.01+00	Black Label	Wallapop	Sin funda
13	Disney/Pixar Monstruos S.A: Isla de los Sustos	\N	2023-08-15	14.18	GOOD	\N	PAL ESPAÑA	PS1	t	2026-06-30 19:06:38.863+00	2026-06-30 19:07:05.18+00	Platinum	Wallapop	Sin funda
14	Disney Dinosaurio	\N	2024-06-11	13.05	GOOD	\N	PAL ESPAÑA	PS1	t	2026-06-30 19:11:34.241+00	2026-06-30 19:12:07.078+00	Black Label	Wallapop	Sin funda
15	Tomb Raider II	\N	2024-03-25	1.00	FAIR	Juego comprado con el FIFA 2004	PAL ESPAÑA	PS1	f	2026-06-30 19:14:33.224+00	2026-06-30 19:15:39.278+00	Black Label	Wallapop	Sin funda
16	El Libro de la Selva: Muevete con Ritmo	\N	2024-06-20	23.53	MINT	\N	PAL ESPAÑA	PS1	t	2026-06-30 19:17:28.566+00	2026-06-30 19:17:45.578+00	Black Label	Wallapop	Sin funda
17	Tony Hawk's: Skateboarding	\N	0004-01-17	15.00	FAIR	\N	PAL ESPAÑA	PS1	t	2026-06-30 19:19:30.471+00	2026-06-30 19:19:47.735+00	Platinum	Wallapop	Sin funda
18	Metal Gear Solid 3:  Snake Eater	\N	2025-09-03	24.98	MINT	Este juego fue comprado con una Memory Card de PlayStation 1	PAL ESPAÑA	PS2	t	2026-06-30 19:24:22.675+00	2026-06-30 19:24:23.468+00	Black Label	Wallapop	Sin funda
19	Grand Theft Auto: San Andreas	\N	2024-12-30	20.30	GOOD	\N	PAL ESPAÑA	PS2	t	2026-06-30 19:40:31.613+00	2026-06-30 19:40:35.147+00	Black Label	Wallapop	Sin funda
20	Grand Theft Auto: Vice City	\N	2025-06-06	17.28	FAIR	\N	PAL ESPAÑA	PS2	f	2026-06-30 19:46:39.702+00	2026-06-30 19:46:41.694+00	Black Label	Wallapop	Sin funda
21	Grand Theft Auto: III	\N	2025-06-06	14.28	FAIR	\N	PAL ESPAÑA	PS2	f	2026-06-30 19:47:15.571+00	2026-06-30 19:47:16.657+00	Black Label	Wallapop	Sin funda
22	Grand Theft Auto: IV	\N	2025-06-11	7.64	MINT	Este juego se compro con el Gran Theft Auto V	PAL ESPAÑA	PS3	t	2026-06-30 19:48:32.444+00	2026-06-30 19:48:32.855+00	Black Label	Wallapop	Sin funda
23	Grand Theft Auto: V	\N	2025-06-11	7.64	MINT	Este juego se compro con el Gran Theft Auto VI	PAL ESPAÑA	PS3	t	2026-06-30 19:48:59.687+00	2026-06-30 19:49:22.258+00	Black Label	Wallapop	Sin funda
24	Grand Theft Auto: San Andreas	\N	2021-07-13	\N	MINT	\N	PAL ESPAÑA	PS3	t	2026-06-30 19:51:16.663+00	2026-06-30 19:51:17.42+00	Black Label	Wallapop	Sin funda
25	The Elder Scrolls V: Skyrim	\N	\N	\N	GOOD	Este juego me vino con la consola PlayStation 3 SuperSlim.	PAL ESPAÑA	PS3	t	2026-06-30 19:54:16.407+00	2026-06-30 19:54:16.838+00	Legendary Edition	Wallapop	Sin funda
26	Final Fantasy X	\N	2026-05-08	9.12	GOOD	Este juego se compro con 2 juegos mas a la vez, Final Fantasy X-2 y Final Fantasy XII	PAL ESPAÑA	PS2	t	2026-06-30 19:57:38.632+00	2026-06-30 19:57:39.214+00	Black Label	Wallapop	Sin funda
27	Final Fantasy X-2	\N	2026-05-08	9.12	GOOD	Este juego se compro con 2 juegos mas a la vez, Final Fantasy X y Final Fantasy XII	PAL ESPAÑA	PS2	f	2026-06-30 19:59:36.641+00	2026-06-30 19:59:37.047+00	Black Label	Wallapop	Sin funda
28	Final Fantasy XII	\N	2026-05-08	9.12	GOOD	Este juego se compro con 2 juegos mas a la vez, Final Fantasy X y Final Fantasy X-2	PAL ESPAÑA	PS2	t	2026-06-30 20:00:51.863+00	2026-06-30 20:00:52.627+00	Black Label	Wallapop	Sin funda
32	Kingdom Hearts II	\N	2026-05-08	15.67	MINT	\N	PAL ESPAÑA	PS2	t	2026-06-30 20:11:15.498+00	2026-06-30 20:11:20.939+00	Black Label	Wallapop	Sin funda
\.


--
-- Data for Name: inventory_game_missing_components; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.inventory_game_missing_components (id, game_id, missingcomponent_id) FROM stdin;
\.


--
-- Data for Name: inventory_itemimage; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.inventory_itemimage (id, object_id, image, uploaded_at, content_type_id) FROM stdin;
48	5	games/rayman-2-5/4.CONTRAPORTADA.webp	2026-06-28 19:31:09.582+00	9
49	5	games/rayman-2-5/3.MANUAL_TARJETA_DE_REGISTRO_Y_DISCO_POR_DETRAS.heic.webp	2026-06-28 19:31:13.045+00	9
50	5	games/rayman-2-5/2.MANUAL_TARJETA_DE_REGISTRO_Y_DISCO_POR_DELANTE.webp	2026-06-28 19:31:17.134+00	9
51	5	games/rayman-2-5/1_msygOQp.PORTADA.webp	2026-06-28 19:31:20.544+00	9
52	6	games/disney-atlantis-el-imperio-perdido-6/5_s42fqPW.LATERAL_QUE_ABRE.webp	2026-06-28 19:34:14.998+00	9
53	6	games/disney-atlantis-el-imperio-perdido-6/4_VKofEo7.LATERAL_BISAGRA.webp	2026-06-28 19:34:18.74+00	9
54	6	games/disney-atlantis-el-imperio-perdido-6/3_AoJtIa3.CONTAPORTADA_MANUAL_Y_DISCO_POR_DETRAS.webp	2026-06-28 19:34:23.983+00	9
55	6	games/disney-atlantis-el-imperio-perdido-6/2_tSm3Lrd.MANUAL_Y_DISCO_POR_DELANTE.webp	2026-06-28 19:34:28.417+00	9
56	6	games/disney-atlantis-el-imperio-perdido-6/1_8nKylmX.PORTADA.webp	2026-06-28 19:34:32.624+00	9
57	7	games/gran-turismo-7/5_5lYDAzJ.LATERAL_QUE_ABRE.webp	2026-06-28 19:39:01.403+00	9
58	7	games/gran-turismo-7/4_4F3Julj.LATERAL_BISAGRA.webp	2026-06-28 19:39:05.738+00	9
60	7	games/gran-turismo-7/3_ONoZr8S.CONTAPORTADA_MANUAL_Y_DISCO_POR_DETRAS.webp	2026-06-28 19:39:17.453+00	9
61	7	games/gran-turismo-7/2_DIUmwsY.MANUAL_Y_DISCO_POR_DELANTE.webp	2026-06-28 19:39:21.404+00	9
62	7	games/gran-turismo-7/1_dArQVDK.PORTADA.webp	2026-06-28 19:39:25.281+00	9
65	10	games/crash-bandicoot-3-warped-10/5_H0PcwMB.LATERAL_QUE_ABRE.webp	2026-06-29 11:39:33.399+00	9
66	10	games/crash-bandicoot-3-warped-10/4_KolWves.LATERAL_BISAGRA.webp	2026-06-29 11:39:36.532+00	9
67	10	games/crash-bandicoot-3-warped-10/3.CONTAPORTADA_MANUAL_Y_DISCOS_POR_DETRAS.webp	2026-06-29 11:39:40.192+00	9
68	10	games/crash-bandicoot-3-warped-10/2.MANUAL_Y_DISCOS_POR_DELANTE.webp	2026-06-29 11:39:45.213+00	9
69	10	games/crash-bandicoot-3-warped-10/1_Y8J5O57.PORTADA.webp	2026-06-29 11:39:49.291+00	9
70	1	accessorys/game-link-cable-game-boy-advance-1/Captura_de_pantalla_2025-12-28_135246.webp	2026-06-29 11:42:07.854+00	7
71	1	accessorys/game-link-cable-game-boy-advance-1/Captura_de_pantalla_2025-12-28_135242.webp	2026-06-29 11:42:12.04+00	7
72	1	accessorys/game-link-cable-game-boy-advance-1/Captura_de_pantalla_2025-12-28_135237.webp	2026-06-29 11:42:14.9+00	7
73	1	accessorys/game-link-cable-game-boy-advance-1/Captura_de_pantalla_2025-12-28_135233.webp	2026-06-29 11:42:18.245+00	7
74	11	games/anna-kournikovas-smash-court-tennis-11/5_BPV7sIV.LATERAL_QUE_ABRE.webp	2026-06-29 12:14:41.465+00	9
75	11	games/anna-kournikovas-smash-court-tennis-11/4_EHhFNFp.LATERAL_BISAGRA.webp	2026-06-29 12:14:44.532+00	9
76	11	games/anna-kournikovas-smash-court-tennis-11/3_8LRQ5Zu.CONTAPORTADA_MANUAL_Y_DISCO_POR_DETRAS.webp	2026-06-29 12:14:47.919+00	9
77	11	games/anna-kournikovas-smash-court-tennis-11/2_d0QEd8j.MANUAL_Y_DISCO_POR_DELANTE.webp	2026-06-29 12:14:51.668+00	9
78	11	games/anna-kournikovas-smash-court-tennis-11/1_wayVeUH.PORTADA.webp	2026-06-29 12:14:56.081+00	9
79	1	consoles/playstation-1-fat-1/IMG20260630123240.webp	2026-06-30 15:46:21.279+00	8
80	1	consoles/playstation-1-fat-1/IMG20260630123202.webp	2026-06-30 15:46:26.045+00	8
81	1	consoles/playstation-1-fat-1/IMG20260630123030.webp	2026-06-30 15:46:32.281+00	8
82	1	consoles/playstation-1-fat-1/IMG20260630123004.webp	2026-06-30 15:46:36.242+00	8
83	1	consoles/playstation-1-fat-1/IMG20260630122722.webp	2026-06-30 15:46:39.754+00	8
84	1	consoles/playstation-1-fat-1/IMG20260630122709.webp	2026-06-30 15:46:43.797+00	8
85	1	consoles/playstation-1-fat-1/IMG20260630122658.webp	2026-06-30 15:46:50.7+00	8
86	1	consoles/playstation-1-fat-1/IMG20260630122450.webp	2026-06-30 15:46:57.386+00	8
87	1	consoles/playstation-1-fat-1/IMG20260630122433.webp	2026-06-30 15:47:01.898+00	8
88	1	consoles/playstation-1-fat-1/IMG20260630122409.webp	2026-06-30 15:47:06.178+00	8
89	1	consoles/playstation-1-fat-1/IMG20260630122356.webp	2026-06-30 15:47:13.756+00	8
90	1	consoles/playstation-1-fat-1/IMG20260630122343.webp	2026-06-30 15:47:18.093+00	8
91	1	consoles/playstation-1-fat-1/IMG20260630122327.webp	2026-06-30 15:47:21.771+00	8
92	2	consoles/psone-2/IMG20260630134457.webp	2026-06-30 16:12:26.837+00	8
93	2	consoles/psone-2/IMG20260630134435.webp	2026-06-30 16:12:31.306+00	8
94	2	consoles/psone-2/IMG20260630134219.webp	2026-06-30 16:12:36.697+00	8
95	2	consoles/psone-2/IMG20260630134211.webp	2026-06-30 16:12:39.999+00	8
96	2	consoles/psone-2/IMG20260630134203.webp	2026-06-30 16:12:48.836+00	8
97	2	consoles/psone-2/IMG20260630134153.webp	2026-06-30 16:12:52.873+00	8
98	2	consoles/psone-2/IMG20260630134043.webp	2026-06-30 16:12:56.893+00	8
99	2	consoles/psone-2/IMG20260630133858.webp	2026-06-30 16:13:05.215+00	8
100	2	consoles/psone-2/IMG20260630133849.webp	2026-06-30 16:13:10+00	8
101	2	consoles/psone-2/IMG20260630133839.webp	2026-06-30 16:13:13.677+00	8
102	2	consoles/psone-2/IMG20260630133822.webp	2026-06-30 16:13:17.611+00	8
103	2	consoles/psone-2/IMG20260630133743.webp	2026-06-30 16:13:21.03+00	8
104	2	consoles/psone-2/IMG20260630133644.webp	2026-06-30 16:13:23.992+00	8
105	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630144123.webp	2026-06-30 16:18:00.505+00	8
106	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630143851.webp	2026-06-30 16:18:05.304+00	8
107	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630143758.webp	2026-06-30 16:18:09.99+00	8
108	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630143528.webp	2026-06-30 16:18:14.923+00	8
109	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630141257.webp	2026-06-30 16:18:19.314+00	8
110	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630141245.webp	2026-06-30 16:18:22.561+00	8
111	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630141234.webp	2026-06-30 16:18:27.375+00	8
112	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630141217.webp	2026-06-30 16:18:32.232+00	8
113	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630141026.webp	2026-06-30 16:18:36.338+00	8
114	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630141009.webp	2026-06-30 16:18:39.401+00	8
115	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630140959.webp	2026-06-30 16:18:43.675+00	8
116	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630140947.webp	2026-06-30 16:18:51.622+00	8
117	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630140938.webp	2026-06-30 16:18:59.252+00	8
118	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630140827.webp	2026-06-30 16:19:04.726+00	8
119	3	consoles/playstation-2-slim-satin-silver-3/IMG20260630140758.webp	2026-06-30 16:19:07.843+00	8
120	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630140329.webp	2026-06-30 16:22:58.15+00	8
121	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630140115.webp	2026-06-30 16:23:03.368+00	8
122	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630140105.webp	2026-06-30 16:23:08.64+00	8
123	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630140056.webp	2026-06-30 16:23:13.046+00	8
124	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630140047.webp	2026-06-30 16:23:16.447+00	8
125	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135945.webp	2026-06-30 16:23:19.445+00	8
126	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135938.webp	2026-06-30 16:23:23.454+00	8
127	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135931.webp	2026-06-30 16:23:27.822+00	8
128	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135925.webp	2026-06-30 16:23:43.121+00	8
129	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135917.webp	2026-06-30 16:23:52.297+00	8
130	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135904.webp	2026-06-30 16:23:55.298+00	8
131	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135255.webp	2026-06-30 16:23:58.75+00	8
132	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135043.webp	2026-06-30 16:24:02.208+00	8
133	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135033.webp	2026-06-30 16:24:09.098+00	8
134	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135025.webp	2026-06-30 16:24:13.39+00	8
135	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135015.webp	2026-06-30 16:24:26.378+00	8
136	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630135005.webp	2026-06-30 16:24:29.248+00	8
137	4	consoles/playstation-2-superslim-bundle-disney-singstar-4/IMG20260630134940.webp	2026-06-30 16:24:33.753+00	8
140	5	consoles/playstation-2-slim-5/IMG20260630150235.webp	2026-06-30 17:29:51.02+00	8
141	5	consoles/playstation-2-slim-5/IMG20260630150225.webp	2026-06-30 17:29:54.602+00	8
142	5	consoles/playstation-2-slim-5/IMG20260630150218.webp	2026-06-30 17:29:58.895+00	8
143	5	consoles/playstation-2-slim-5/IMG20260630150211.webp	2026-06-30 17:30:01.831+00	8
146	6	consoles/playstation-3-fat-6/IMG20260630145846.webp	2026-06-30 17:39:36.246+00	8
147	6	consoles/playstation-3-fat-6/IMG20260630145519.webp	2026-06-30 17:39:43.707+00	8
148	6	consoles/playstation-3-fat-6/IMG20260630145500.webp	2026-06-30 17:39:49.638+00	8
149	6	consoles/playstation-3-fat-6/IMG20260630145451.webp	2026-06-30 17:39:54.077+00	8
150	6	consoles/playstation-3-fat-6/IMG20260630145436.webp	2026-06-30 17:39:58.45+00	8
151	6	consoles/playstation-3-fat-6/IMG20260630145335.webp	2026-06-30 17:40:03.821+00	8
152	6	consoles/playstation-3-fat-6/IMG20260630145242.webp	2026-06-30 17:40:07.296+00	8
153	6	consoles/playstation-3-fat-6/IMG20260630145034.webp	2026-06-30 17:40:12.334+00	8
154	6	consoles/playstation-3-fat-6/IMG20260630145019.webp	2026-06-30 17:40:15.869+00	8
155	6	consoles/playstation-3-fat-6/IMG20260630145005.webp	2026-06-30 17:40:19.165+00	8
156	6	consoles/playstation-3-fat-6/IMG20260630144953.webp	2026-06-30 17:40:22.632+00	8
157	6	consoles/playstation-3-fat-6/IMG20260630144941.webp	2026-06-30 17:40:26.384+00	8
158	6	consoles/playstation-3-fat-6/IMG20260630144923.webp	2026-06-30 17:40:31.677+00	8
159	6	consoles/playstation-3-fat-6/IMG20260630144837.webp	2026-06-30 17:40:36.756+00	8
160	6	consoles/playstation-3-fat-6/IMG20260630144814.webp	2026-06-30 17:40:40.622+00	8
161	6	consoles/playstation-3-fat-6/IMG20260630144755.webp	2026-06-30 17:40:44.483+00	8
162	6	consoles/playstation-3-fat-6/IMG20260630144745.webp	2026-06-30 17:40:47.949+00	8
163	6	consoles/playstation-3-fat-6/IMG20260630144727.webp	2026-06-30 17:40:51.101+00	8
164	7	consoles/playstation-3-superslim-7/IMG20260630124705.webp	2026-06-30 17:48:14.896+00	8
165	7	consoles/playstation-3-superslim-7/IMG20260630124629.webp	2026-06-30 17:48:18.539+00	8
166	7	consoles/playstation-3-superslim-7/IMG20260630124401.webp	2026-06-30 17:48:21.865+00	8
167	7	consoles/playstation-3-superslim-7/IMG20260630124321.webp	2026-06-30 17:48:25.927+00	8
168	7	consoles/playstation-3-superslim-7/IMG20260630124037.webp	2026-06-30 17:48:29.37+00	8
169	7	consoles/playstation-3-superslim-7/IMG20260630123821.webp	2026-06-30 17:48:38.566+00	8
170	7	consoles/playstation-3-superslim-7/IMG20260630123811.webp	2026-06-30 17:49:01.728+00	8
171	7	consoles/playstation-3-superslim-7/IMG20260630123759.webp	2026-06-30 17:49:05.658+00	8
172	7	consoles/playstation-3-superslim-7/IMG20260630123738.webp	2026-06-30 17:49:09.741+00	8
173	7	consoles/playstation-3-superslim-7/IMG20260630123716.webp	2026-06-30 17:49:14.961+00	8
174	8	consoles/playstation-4-slim-8/IMG20260630130615.webp	2026-06-30 17:57:01.95+00	8
175	8	consoles/playstation-4-slim-8/IMG20260630130503.webp	2026-06-30 17:57:05.898+00	8
176	8	consoles/playstation-4-slim-8/IMG20260630130402.webp	2026-06-30 17:57:09.534+00	8
177	8	consoles/playstation-4-slim-8/IMG20260630130352.webp	2026-06-30 17:57:17.745+00	8
178	8	consoles/playstation-4-slim-8/IMG20260630130019.webp	2026-06-30 17:57:21.368+00	8
179	8	consoles/playstation-4-slim-8/IMG20260630130006.webp	2026-06-30 18:02:07.287+00	8
180	8	consoles/playstation-4-slim-8/IMG20260630125940.webp	2026-06-30 18:02:10.818+00	8
181	8	consoles/playstation-4-slim-8/IMG20260630125909.webp	2026-06-30 18:02:15.456+00	8
182	8	consoles/playstation-4-slim-8/IMG20260630125545.webp	2026-06-30 18:02:19.649+00	8
183	8	consoles/playstation-4-slim-8/IMG20260630125529.webp	2026-06-30 18:02:27.595+00	8
184	8	consoles/playstation-4-slim-8/IMG20260630125517.webp	2026-06-30 18:02:31.136+00	8
185	8	consoles/playstation-4-slim-8/IMG20260630125505.webp	2026-06-30 18:02:35.108+00	8
186	8	consoles/playstation-4-slim-8/IMG20260630125453.webp	2026-06-30 18:02:40.16+00	8
187	8	consoles/playstation-4-slim-8/IMG20260630125444.webp	2026-06-30 18:02:50.657+00	8
188	8	consoles/playstation-4-slim-8/IMG20260630125414.webp	2026-06-30 18:02:54.244+00	8
189	8	consoles/playstation-4-slim-8/IMG20260630125332.webp	2026-06-30 18:03:04.171+00	8
190	8	consoles/playstation-4-slim-8/IMG20260630125315.webp	2026-06-30 18:03:07.996+00	8
191	8	consoles/playstation-4-slim-8/IMG20260630125257.webp	2026-06-30 18:03:12.266+00	8
192	8	consoles/playstation-4-slim-8/IMG20260630125216.webp	2026-06-30 18:03:16.389+00	8
193	8	consoles/playstation-4-slim-8/IMG20260630125157.webp	2026-06-30 18:03:21.572+00	8
194	9	consoles/psp-slim-9/IMG20260630122021.webp	2026-06-30 18:11:03.8+00	8
195	9	consoles/psp-slim-9/IMG20260630122013.webp	2026-06-30 18:11:11.332+00	8
196	9	consoles/psp-slim-9/IMG20260630122003.webp	2026-06-30 18:11:15.191+00	8
197	9	consoles/psp-slim-9/IMG20260630121833.webp	2026-06-30 18:11:18.534+00	8
198	9	consoles/psp-slim-9/IMG20260630121644.webp	2026-06-30 18:11:22.794+00	8
199	9	consoles/psp-slim-9/IMG20260630121615.webp	2026-06-30 18:11:25.978+00	8
200	9	consoles/psp-slim-9/IMG20260630121443.webp	2026-06-30 18:11:35.317+00	8
201	9	consoles/psp-slim-9/IMG20260630121434.webp	2026-06-30 18:11:39.049+00	8
202	9	consoles/psp-slim-9/IMG20260630121334.webp	2026-06-30 18:11:42.481+00	8
203	9	consoles/psp-slim-9/IMG20260630121325.webp	2026-06-30 18:11:50.682+00	8
204	9	consoles/psp-slim-9/IMG20260630121314.webp	2026-06-30 18:11:55.268+00	8
205	9	consoles/psp-slim-9/IMG20260630121304.webp	2026-06-30 18:11:58.201+00	8
206	9	consoles/psp-slim-9/IMG20260630121256.webp	2026-06-30 18:12:01.733+00	8
207	9	consoles/psp-slim-9/IMG20260630121241.webp	2026-06-30 18:12:05.2+00	8
208	9	consoles/psp-slim-9/IMG20260630121145.webp	2026-06-30 18:12:10.545+00	8
209	9	consoles/psp-slim-9/IMG20260630121134.webp	2026-06-30 18:12:16.392+00	8
210	9	consoles/psp-slim-9/IMG20260630121122.webp	2026-06-30 18:12:19.715+00	8
212	9	consoles/psp-slim-9/IMG20260630121108.webp	2026-06-30 18:12:32.108+00	8
213	9	consoles/psp-slim-9/IMG20260630121058.webp	2026-06-30 18:12:36.685+00	8
214	9	consoles/psp-slim-9/IMG20260630121048.webp	2026-06-30 18:12:40.541+00	8
215	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120815.webp	2026-06-30 18:17:50.861+00	8
216	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120716.webp	2026-06-30 18:17:54.813+00	8
217	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120649.webp	2026-06-30 18:17:58.431+00	8
218	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120632.webp	2026-06-30 18:18:03.52+00	8
219	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120548.webp	2026-06-30 18:18:07.676+00	8
220	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120529.webp	2026-06-30 18:18:11.19+00	8
221	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120511.webp	2026-06-30 18:18:16.187+00	8
222	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120124.webp	2026-06-30 18:18:20.012+00	8
223	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120108.webp	2026-06-30 18:18:23.272+00	8
224	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120101.webp	2026-06-30 18:18:30.912+00	8
225	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120054.webp	2026-06-30 18:18:35.347+00	8
226	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120045.webp	2026-06-30 18:18:38.746+00	8
227	10	consoles/new-nintendo-3ds-xl-10/IMG20260630120036.webp	2026-06-30 18:18:41.923+00	8
228	11	consoles/game-boy-advance-11/IMG20260630115705.webp	2026-06-30 18:24:50.048+00	8
229	11	consoles/game-boy-advance-11/IMG20260630115655.webp	2026-06-30 18:24:53.584+00	8
230	11	consoles/game-boy-advance-11/IMG20260630115629.webp	2026-06-30 18:24:56.8+00	8
231	11	consoles/game-boy-advance-11/IMG20260630115619.webp	2026-06-30 18:25:00.528+00	8
232	11	consoles/game-boy-advance-11/IMG20260630115555.webp	2026-06-30 18:25:03.776+00	8
233	11	consoles/game-boy-advance-11/IMG20260630115542.webp	2026-06-30 18:25:08.223+00	8
234	11	consoles/game-boy-advance-11/IMG20260630115536.webp	2026-06-30 18:25:11.369+00	8
235	11	consoles/game-boy-advance-11/IMG20260630115402.webp	2026-06-30 18:25:14.929+00	8
236	11	consoles/game-boy-advance-11/IMG20260630115345.webp	2026-06-30 18:25:18.481+00	8
237	11	consoles/game-boy-advance-11/IMG20260630115330.webp	2026-06-30 18:25:21.647+00	8
238	11	consoles/game-boy-advance-11/IMG20260630115112.webp	2026-06-30 18:25:25.931+00	8
239	11	consoles/game-boy-advance-11/IMG20260630115105.webp	2026-06-30 18:25:29.406+00	8
240	11	consoles/game-boy-advance-11/IMG20260630115056.webp	2026-06-30 18:25:33.337+00	8
241	11	consoles/game-boy-advance-11/IMG20260630115048.webp	2026-06-30 18:25:37.039+00	8
242	11	consoles/game-boy-advance-11/IMG20260630115034.webp	2026-06-30 18:25:40.542+00	8
243	11	consoles/game-boy-advance-11/IMG20260630115021.webp	2026-06-30 18:25:43.769+00	8
244	13	consoles/game-boy-13/IMG20260630150312.webp	2026-06-30 18:55:56.504+00	8
245	13	consoles/game-boy-13/IMG20260630150305.webp	2026-06-30 18:56:00.401+00	8
246	12	games/fifa-2004-12/5.LATERAL_QUE_ABRE.webp	2026-06-30 19:05:01.238+00	9
247	12	games/fifa-2004-12/4.LATERAL_BISAGRA.webp	2026-06-30 19:05:04.961+00	9
248	12	games/fifa-2004-12/3.CONTAPORTADA_MANUAL_Y_DISCO_POR_DETRAS.webp	2026-06-30 19:05:08.397+00	9
249	12	games/fifa-2004-12/2.MANUAL_Y_DISCO_POR_DELANTE.webp	2026-06-30 19:05:12.139+00	9
250	12	games/fifa-2004-12/1.PORTADA.webp	2026-06-30 19:05:15.821+00	9
251	13	games/disneypixar-monstruos-sa-isla-de-los-sustos-13/5.LATERAL_QUE_ABRE.webp	2026-06-30 19:06:39.744+00	9
252	13	games/disneypixar-monstruos-sa-isla-de-los-sustos-13/4.LATERAL_BISAGRA.webp	2026-06-30 19:06:43.609+00	9
253	13	games/disneypixar-monstruos-sa-isla-de-los-sustos-13/3.CONTAPORTADA_MANUAL_Y_DISCO_POR_DETRAS.webp	2026-06-30 19:06:47.126+00	9
254	13	games/disneypixar-monstruos-sa-isla-de-los-sustos-13/2.MANUAL_Y_DISCO_POR_DELANTE.webp	2026-06-30 19:06:51.387+00	9
255	13	games/disneypixar-monstruos-sa-isla-de-los-sustos-13/1.PORTADA.webp	2026-06-30 19:06:56.471+00	9
256	14	games/disney-dinosaurio-14/7.LATERAL_QUE_ABRE.webp	2026-06-30 19:11:35.184+00	9
257	14	games/disney-dinosaurio-14/6.LATERAL_BISAGRA.webp	2026-06-30 19:11:39.534+00	9
258	14	games/disney-dinosaurio-14/5.PANFLETO_DESPLEGADO.webp	2026-06-30 19:11:42.627+00	9
259	14	games/disney-dinosaurio-14/4.PARTE_DE_PANFLETO.webp	2026-06-30 19:11:46.51+00	9
260	14	games/disney-dinosaurio-14/3.MANUAL_PANFLETO_TARJETA_DE_REGISTRO_Y_DISCO_POR_DETRAS.webp	2026-06-30 19:11:51.08+00	9
261	14	games/disney-dinosaurio-14/2.MANUAL_PANFLETO_TARJETA_DE_REGISTRO_Y_DISCO_POR_DELANTE.webp	2026-06-30 19:11:55.097+00	9
262	14	games/disney-dinosaurio-14/1.PORTADA.webp	2026-06-30 19:11:59.095+00	9
22	1	games/metal-gear-solid-1/8.LATERAL_QUE_ABRE.webp	2026-06-28 18:44:36.751+00	9
23	1	games/metal-gear-solid-1/7.LATERAL_BISAGRA.webp	2026-06-28 18:44:40.573+00	9
24	1	games/metal-gear-solid-1/6.POSTER_DE_SILENT_HILL.webp	2026-06-28 18:44:44.253+00	9
25	1	games/metal-gear-solid-1/5.CONTRAPORTADA_Y_POSTER_CONTROLES.webp	2026-06-28 18:44:48.543+00	9
26	1	games/metal-gear-solid-1/4.DSICOS_1_Y_2_POSTER_SILENT_HILL_Y_PANFLETO_DE_KONAMI_1999_POR_DETRAS.webp	2026-06-28 18:44:53.902+00	9
27	1	games/metal-gear-solid-1/3.DSICOS_1_Y_2_POSTER_SILENT_HILL_Y_PANFLETO_DE_KONAMI_1999_POR_DELANTE.webp	2026-06-28 18:44:59.081+00	9
28	1	games/metal-gear-solid-1/3.DEMO_SILENT_HILL_Y_MANUAL_POR_DETRAS.webp	2026-06-28 18:45:09.261+00	9
29	1	games/metal-gear-solid-1/2.DEMO_SILENT_HILL_Y_MANUAL_POR_DELANTE.webp	2026-06-28 18:45:13.693+00	9
30	1	games/metal-gear-solid-1/1.PORTADA.webp	2026-06-28 18:45:18.388+00	9
31	2	games/final-fantasy-viii-2/6.LATERAL_QUE_ABRE.webp	2026-06-28 19:19:35.469+00	9
32	2	games/final-fantasy-viii-2/5.LATERAL_BISAGRA.webp	2026-06-28 19:19:41.596+00	9
33	2	games/final-fantasy-viii-2/4.CONTRAPORTADA_Y_DISCOS_POR_DETRAS.webp	2026-06-28 19:19:45.518+00	9
34	2	games/final-fantasy-viii-2/3.MANUAL_Y_DISCOS_3_Y_4_POR_DETRAS.webp	2026-06-28 19:19:50.479+00	9
35	2	games/final-fantasy-viii-2/2.MANUAL_Y_DISCOS_1_Y_2_POR_DELANTE.webp	2026-06-28 19:19:54.753+00	9
36	2	games/final-fantasy-viii-2/1_qTH2sQo.PORTADA.webp	2026-06-28 19:19:58.815+00	9
37	3	games/mickey-wild-advanture-3/5.LATERAL_QUE_ABRE.webp	2026-06-28 19:22:08.38+00	9
38	3	games/mickey-wild-advanture-3/3.LATERAL_BISAGRA.webp	2026-06-28 19:22:11.893+00	9
39	3	games/mickey-wild-advanture-3/2.CONTRAPORTADA.webp	2026-06-28 19:22:15.278+00	9
40	3	games/mickey-wild-advanture-3/1_bU89uws.PORTADA.webp	2026-06-28 19:22:18.9+00	9
41	4	games/rayman-4/5_uEPEYgL.LATERAL_QUE_ABRE.webp	2026-06-28 19:26:18.257+00	9
42	4	games/rayman-4/4.LATERAL_BISAGRA.webp	2026-06-28 19:26:22.096+00	9
43	4	games/rayman-4/3.CONTAPORTADA_MANUAL_Y_DISCO_POR_DETRAS.webp	2026-06-28 19:26:25.443+00	9
44	4	games/rayman-4/2.MANUAL_Y_DISCO_POR_DELANTE.webp	2026-06-28 19:26:28.965+00	9
45	4	games/rayman-4/1_hiJyjGK.PORTADA.webp	2026-06-28 19:26:33.436+00	9
46	5	games/rayman-2-5/6_REuL3Vt.LATERAL_QUE_ABRE.webp	2026-06-28 19:31:01.729+00	9
47	5	games/rayman-2-5/5_lqydsv9.LATERAL_BISAGRA.webp	2026-06-28 19:31:05.249+00	9
145	6	consoles/playstation-3-fat-6/IMG20260630145854.webp	2026-06-30 17:39:32.759+00	8
263	15	games/tomb-raider-ii-15/2.DISCO_POR_DETRAS.webp	2026-06-30 19:14:34.114+00	9
264	15	games/tomb-raider-ii-15/1.DISCO_POR_DELANTE.webp	2026-06-30 19:14:37.794+00	9
265	16	games/el-libro-de-la-selva-muevete-con-ritmo-16/5.LATERAL_QUE_ABRE.webp	2026-06-30 19:17:29.42+00	9
266	16	games/el-libro-de-la-selva-muevete-con-ritmo-16/4.LATERAL_BISAGRA.webp	2026-06-30 19:17:33.113+00	9
267	16	games/el-libro-de-la-selva-muevete-con-ritmo-16/3.CONTAPORTADA_MANUAL_Y_DISCO_POR_DETRAS.webp	2026-06-30 19:17:37.125+00	9
268	16	games/el-libro-de-la-selva-muevete-con-ritmo-16/2.MANUAL_Y_DISCO_POR_DELANTE.webp	2026-06-30 19:17:41.316+00	9
269	16	games/el-libro-de-la-selva-muevete-con-ritmo-16/1.PORTADA.webp	2026-06-30 19:17:44.932+00	9
270	17	games/tony-hawks-skateboarding-17/5.LATERAL_QUE_ABRE.webp	2026-06-30 19:19:31.262+00	9
271	17	games/tony-hawks-skateboarding-17/4.LATERAL_BISAGRA.webp	2026-06-30 19:19:34.419+00	9
272	17	games/tony-hawks-skateboarding-17/3.CONTAPORTADA_MANUAL_Y_DISCO_POR_DETRAS.webp	2026-06-30 19:19:38.514+00	9
273	17	games/tony-hawks-skateboarding-17/2.MANUAL_Y_DISCO_POR_DELANTE.webp	2026-06-30 19:19:42.337+00	9
274	17	games/tony-hawks-skateboarding-17/1.PORTADA.webp	2026-06-30 19:19:46.276+00	9
276	6	accessorys/demo-winter-releases-98-6/DISCO.webp	2026-07-03 16:13:32.121+00	7
277	6	accessorys/demo-winter-releases-98-6/demo_Winter_Releases_98.webp	2026-07-03 16:13:36.492+00	7
\.


--
-- Data for Name: inventory_missingcomponent; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.inventory_missingcomponent (id, name) FROM stdin;
1	Caja
2	Manuales
3	Cable
4	Folleto
5	Poster
6	Mando
7	Euroconector
8	Cartucho
9	DIsco
10	Demo
11	Insert
12	Plasticos
13	Tarjeta de registro
14	Mapa
\.


--
-- Data for Name: user_user; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_user (id, password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email) FROM stdin;
1	pbkdf2_sha256$1200000$xtnt56dcbFbwlccCPMoTRe$bpYPVnhkTReL7UHJU+Dg/7n4xIYRQgyGc7vA0vDHJU8=	2026-09-29 17:43:26.444465+00	t	antoniorb1913			t	t	2026-07-01 14:49:24.378402+00	antoniorb1913@gmail.com
\.


--
-- Data for Name: user_user_groups; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: user_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 21, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 31, true);


--
-- Name: inventory_accessory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.inventory_accessory_id_seq', 6, true);


--
-- Name: inventory_accessory_missing_components_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.inventory_accessory_missing_components_id_seq', 1, true);


--
-- Name: inventory_console_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.inventory_console_id_seq', 13, true);


--
-- Name: inventory_console_missing_components_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.inventory_console_missing_components_id_seq', 25, true);


--
-- Name: inventory_game_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.inventory_game_id_seq', 38, true);


--
-- Name: inventory_game_missing_components_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.inventory_game_missing_components_id_seq', 18, true);


--
-- Name: inventory_itemimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.inventory_itemimage_id_seq', 277, true);


--
-- Name: inventory_missingcomponent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.inventory_missingcomponent_id_seq', 14, true);


--
-- Name: user_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_user_groups_id_seq', 1, false);


--
-- Name: user_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_user_id_seq', 1, true);


--
-- Name: user_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: inventory_accessory_missing_components inventory_accessory_miss_accessory_id_missingcomp_f0fe3a17_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_accessory_missing_components
    ADD CONSTRAINT inventory_accessory_miss_accessory_id_missingcomp_f0fe3a17_uniq UNIQUE (accessory_id, missingcomponent_id);


--
-- Name: inventory_accessory_missing_components inventory_accessory_missing_components_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_accessory_missing_components
    ADD CONSTRAINT inventory_accessory_missing_components_pkey PRIMARY KEY (id);


--
-- Name: inventory_accessory inventory_accessory_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_accessory
    ADD CONSTRAINT inventory_accessory_pkey PRIMARY KEY (id);


--
-- Name: inventory_console_missing_components inventory_console_missin_console_id_missingcompon_621d5101_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_console_missing_components
    ADD CONSTRAINT inventory_console_missin_console_id_missingcompon_621d5101_uniq UNIQUE (console_id, missingcomponent_id);


--
-- Name: inventory_console_missing_components inventory_console_missing_components_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_console_missing_components
    ADD CONSTRAINT inventory_console_missing_components_pkey PRIMARY KEY (id);


--
-- Name: inventory_console inventory_console_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_console
    ADD CONSTRAINT inventory_console_pkey PRIMARY KEY (id);


--
-- Name: inventory_game_missing_components inventory_game_missing_c_game_id_missingcomponent_956ccee2_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_game_missing_components
    ADD CONSTRAINT inventory_game_missing_c_game_id_missingcomponent_956ccee2_uniq UNIQUE (game_id, missingcomponent_id);


--
-- Name: inventory_game_missing_components inventory_game_missing_components_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_game_missing_components
    ADD CONSTRAINT inventory_game_missing_components_pkey PRIMARY KEY (id);


--
-- Name: inventory_game inventory_game_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_game
    ADD CONSTRAINT inventory_game_pkey PRIMARY KEY (id);


--
-- Name: inventory_itemimage inventory_itemimage_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_itemimage
    ADD CONSTRAINT inventory_itemimage_pkey PRIMARY KEY (id);


--
-- Name: inventory_missingcomponent inventory_missingcomponent_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_missingcomponent
    ADD CONSTRAINT inventory_missingcomponent_name_key UNIQUE (name);


--
-- Name: inventory_missingcomponent inventory_missingcomponent_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_missingcomponent
    ADD CONSTRAINT inventory_missingcomponent_pkey PRIMARY KEY (id);


--
-- Name: user_user user_user_email_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_email_key UNIQUE (email);


--
-- Name: user_user_groups user_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_pkey PRIMARY KEY (id);


--
-- Name: user_user_groups user_user_groups_user_id_group_id_bb60391f_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_user_id_group_id_bb60391f_uniq UNIQUE (user_id, group_id);


--
-- Name: user_user user_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_pkey PRIMARY KEY (id);


--
-- Name: user_user_user_permissions user_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: user_user_user_permissions user_user_user_permissions_user_id_permission_id_64f4d5b8_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_user_id_permission_id_64f4d5b8_uniq UNIQUE (user_id, permission_id);


--
-- Name: user_user user_user_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: inventory_accessory_missin_missingcomponent_id_eab6ff76; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX inventory_accessory_missin_missingcomponent_id_eab6ff76 ON public.inventory_accessory_missing_components USING btree (missingcomponent_id);


--
-- Name: inventory_accessory_missing_components_accessory_id_c39488ae; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX inventory_accessory_missing_components_accessory_id_c39488ae ON public.inventory_accessory_missing_components USING btree (accessory_id);


--
-- Name: inventory_console_missing__missingcomponent_id_4f31f048; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX inventory_console_missing__missingcomponent_id_4f31f048 ON public.inventory_console_missing_components USING btree (missingcomponent_id);


--
-- Name: inventory_console_missing_components_console_id_95ef8d5a; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX inventory_console_missing_components_console_id_95ef8d5a ON public.inventory_console_missing_components USING btree (console_id);


--
-- Name: inventory_game_missing_components_game_id_3139dad6; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX inventory_game_missing_components_game_id_3139dad6 ON public.inventory_game_missing_components USING btree (game_id);


--
-- Name: inventory_game_missing_components_missingcomponent_id_54277e44; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX inventory_game_missing_components_missingcomponent_id_54277e44 ON public.inventory_game_missing_components USING btree (missingcomponent_id);


--
-- Name: inventory_itemimage_content_type_id_1f3f645a; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX inventory_itemimage_content_type_id_1f3f645a ON public.inventory_itemimage USING btree (content_type_id);


--
-- Name: inventory_missingcomponent_name_a8f61131_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX inventory_missingcomponent_name_a8f61131_like ON public.inventory_missingcomponent USING btree (name varchar_pattern_ops);


--
-- Name: user_user_email_1c6f3d1a_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX user_user_email_1c6f3d1a_like ON public.user_user USING btree (email varchar_pattern_ops);


--
-- Name: user_user_groups_group_id_c57f13c0; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX user_user_groups_group_id_c57f13c0 ON public.user_user_groups USING btree (group_id);


--
-- Name: user_user_groups_user_id_13f9a20d; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX user_user_groups_user_id_13f9a20d ON public.user_user_groups USING btree (user_id);


--
-- Name: user_user_user_permissions_permission_id_ce49d4de; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX user_user_user_permissions_permission_id_ce49d4de ON public.user_user_user_permissions USING btree (permission_id);


--
-- Name: user_user_user_permissions_user_id_31782f58; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX user_user_user_permissions_user_id_31782f58 ON public.user_user_user_permissions USING btree (user_id);


--
-- Name: user_user_username_e2bdfe0c_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX user_user_username_e2bdfe0c_like ON public.user_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_accessory_missing_components inventory_accessory__accessory_id_c39488ae_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_accessory_missing_components
    ADD CONSTRAINT inventory_accessory__accessory_id_c39488ae_fk_inventory FOREIGN KEY (accessory_id) REFERENCES public.inventory_accessory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_accessory_missing_components inventory_accessory__missingcomponent_id_eab6ff76_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_accessory_missing_components
    ADD CONSTRAINT inventory_accessory__missingcomponent_id_eab6ff76_fk_inventory FOREIGN KEY (missingcomponent_id) REFERENCES public.inventory_missingcomponent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_console_missing_components inventory_console_mi_console_id_95ef8d5a_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_console_missing_components
    ADD CONSTRAINT inventory_console_mi_console_id_95ef8d5a_fk_inventory FOREIGN KEY (console_id) REFERENCES public.inventory_console(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_console_missing_components inventory_console_mi_missingcomponent_id_4f31f048_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_console_missing_components
    ADD CONSTRAINT inventory_console_mi_missingcomponent_id_4f31f048_fk_inventory FOREIGN KEY (missingcomponent_id) REFERENCES public.inventory_missingcomponent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_game_missing_components inventory_game_missi_game_id_3139dad6_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_game_missing_components
    ADD CONSTRAINT inventory_game_missi_game_id_3139dad6_fk_inventory FOREIGN KEY (game_id) REFERENCES public.inventory_game(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_game_missing_components inventory_game_missi_missingcomponent_id_54277e44_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_game_missing_components
    ADD CONSTRAINT inventory_game_missi_missingcomponent_id_54277e44_fk_inventory FOREIGN KEY (missingcomponent_id) REFERENCES public.inventory_missingcomponent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_itemimage inventory_itemimage_content_type_id_1f3f645a_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.inventory_itemimage
    ADD CONSTRAINT inventory_itemimage_content_type_id_1f3f645a_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_groups user_user_groups_group_id_c57f13c0_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_group_id_c57f13c0_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_groups user_user_groups_user_id_13f9a20d_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_user_id_13f9a20d_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_user_permissions user_user_user_permi_permission_id_ce49d4de_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permi_permission_id_ce49d4de_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_user_permissions user_user_user_permissions_user_id_31782f58_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_user_id_31782f58_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict p26dY9ZM7KoQEkAfYI5HIj3VpTuXcAv9Z5LjhUWfnKY9PwfecebAp0CmgWN4pqc

