services:
  # --- SERVICIO DE BASE DE DATOS ---
  db:
    container_name: retro_db    # Nombre fijo para el contenedor (más fácil de identificar)
    image: postgres:16          # Usa la imagen oficial de PostgreSQL versión 16
    restart: unless-stopped     # Se reinicia solo si falla o si reinicias el PC (salvo que lo pares tú)
    ports:
      - "5432:5432"             # Mapea el puerto [PC]:[Contenedor]. Puedes conectar un gestor externo (como DBeaver)
    volumes:
      - retro_db_data:/var/lib/postgresql/data  # Persistencia: los datos no se borran al apagar el contenedor
    
    # --- CAMBIO IMPORTANTE AQUÍ: Se usa env_file para leer el archivo .env ---
    env_file:
      - .env                    # Aquí Docker lee POSTGRES_DB, POSTGRES_USER y POSTGRES_PASSWORD
    
    healthcheck:                # El "médico": revisa si la DB está lista para recibir conexiones
      test: ["CMD-SHELL", "pg_isready -U admin -d retro_db"] # Comando que verifica la salud usando el usuario admin
      interval: 5s              # Lo intenta cada 5 segundos
      timeout: 5s               # Tiempo máximo de espera por intento
      retries: 10                # Si falla 5 veces seguidas, marca el contenedor como "unhealthy"

  # --- SERVICIO DE LA APP (DJANGO) ---
  app:
    container_name: retro_app
    build: .                    # Busca el "Dockerfile" en la carpeta actual para construir la imagen
    depends_on:                 # ORDEN DE ARRANQUE
      db:
        condition: service_healthy # NO arranca la app hasta que la DB pase el healthcheck (médico) de arriba
    restart: unless-stopped
    ports:
      - "8000:8000"             # Acceso desde tu navegador en http://localhost:8000
    volumes:
      - .:/app                  # MODO DESARROLLO: sincroniza tus archivos locales con el contenedor. 
                                # Si cambias código en Windows, se aplica en el contenedor al instante.
    
    # --- CAMBIO IMPORTANTE AQUÍ: Se usa env_file para leer el archivo .env ---
    env_file:
      - .env                    # Aquí Django lee DB_NAME, DB_USER, SECRET_KEY, etc.

# --- DEFINICIÓN DE VOLÚMENES ---
volumes:
  retro_db_data:                # Crea el "disco duro" virtual para la base de datos