services:
  # --- SERVICIO DE BASE DE DATOS (PostgreSQL) ---
  db:
    container_name: retro_db    # Nombre fijo para identificarlo fácilmente en Docker Desktop
    image: postgres:16          # Usamos la versión 16 oficial (estable y moderna)
    restart: unless-stopped     # Se reinicia solo si falla, pero respeta si tú lo apagas manualmente
    ports:
      - "5433:5432"             # Mapeo de puertos [Tu PC]:[Contenedor] para usar DBeaver o pgAdmin
    volumes:
      - retro_db_data:/var/lib/postgresql/data  # Persistencia: Tus juegos y datos no se borran al apagar
    
    # --- CONFIGURACIÓN POR ARCHIVO EXTERNO ---
    env_file:
      - .env                    # Lee POSTGRES_DB, POSTGRES_USER y POSTGRES_PASSWORD desde tu .env
    
    # --- EL "MÉDICO" DEL SISTEMA (Healthcheck) ---
    healthcheck:
      # Verifica que la DB esté lista. Usamos $$ para que Docker lea la variable del .env correctamente
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s              # Revisa el estado cada 5 segundos
      timeout: 5s               # Si tarda más de 5s en responder, el intento falla
      retries: 10               # Si falla 10 veces, marca el contenedor como "unhealthy" (enfermo)

  # --- SERVICIO DE LA APP (DJANGO) ---
  app:
    container_name: retro_app
    build: .                    # Construye la imagen usando tu Dockerfile optimizado
    depends_on:
      db:
        condition: service_healthy # LA CLAVE: No arranca Django hasta que la DB esté 100% lista
    restart: unless-stopped
    ports:
      - "8000:8000"             # Tu puerta de acceso: http://localhost:8000
    
    # --- SINCRONIZACIÓN Y VELOCIDAD ---
    volumes:
      - .:/app                  # Mapeo en tiempo real: Si guardas un cambio en Windows, se aplica al instante
      - static_volume:/app/staticfiles # TRUCO PRO: Volumen aislado para evitar errores de archivos 0 bytes
    
    # --- CARGA DE SECRETOS ---
    env_file:
      - .env                    # Pasa todas tus llaves secretas y rutas a Django de forma segura

# --- DEFINICIÓN DE DISCOS DUROS VIRTUALES (Volúmenes) ---
volumes:
  retro_db_data:                # Almacena toda tu base de datos de forma segura
  static_volume:                # Almacena los CSS y JS optimizados para que la web cargue rápido