version: "3.9"

services:
  db:
    container_name: retro_db
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - retro_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=retro_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d retro_db"]
      interval: 2s
      timeout: 2s
      retries: 20

  app:
    container_name: retro_app
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=EtiinnN6jzLNnvllA8jKj5eOjOdsZTUj-jqnOAho6m_8nkal4jprqgTkY72knS5zOfY
      - DB_NAME=retro_db
      - DB_USER=admin
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  retro_db_data: