"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import environ
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


env = environ.Env(
    DJANGO_DEBUG=(bool, False) # Si no encuentra la variable DJANGO_DEBUG en el .env, 
                                # por defecto será False (Seguro en producción)
)

# 3. Leemos el archivo .env apuntando a la raíz del proyecto
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# ==============================================================================
# VARIABLES CONFIGURADAS DESDE EL ENTRONO
# ==============================================================================

# Si no encuentra la clave, explota por seguridad (Fail-Fast)
SECRET_KEY = env('DJANGO_SECRET_KEY')

# Parsea el texto automáticamente a un Booleano real de Python
DEBUG = env('DJANGO_DEBUG')

# Parsea una lista separada por comas (ej: localhost,127.0.0.1) a una Lista de Python
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librerías de terceros (Instaladas vía pip)
    'rest_framework',
    'rest_framework_simplejwt',  # <-- ¡Imprescindible para el JWT!
    'corsheaders',                # <-- ¡Imprescindible para conectar con Angular!
    'drf_spectacular',
    
    # Tus aplicaciones locales
    'user',
    # 'inventory', (Cuando la crees)
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Si 'DB_HOST' existe en el entorno (porque Docker lo inyectó), usa ese.
# Si NO existe (porque estás en local sin Docker), por defecto usa 'localhost'.
DB_HOST = env('DB_HOST', default='localhost')


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'PORT': env('DB_PORT'),
        'HOST': DB_HOST,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Tiempo de duración del token
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7)
}

# Configuración de Spectacular --> opcional pero recomendable
SPECTACULAR_SETTINGS = {
    'TITLE': 'Retro Inventory API',
    'DESCRIPTION': 'API para la gestión de inventario de consolas y juegos retro, integrada con Angular y JWT.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # Esto oculta el propio endpoint del esquema dentro de la lista de Swagger para que no ensucie la vista de tus rutas
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = './static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'user.User'