# Generated by Django 6.0.6 on 2026-06-27 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='items/%Y/%m/', verbose_name='Foto')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('SEALED', 'Precintado'), ('MINT', 'Como nuevo'), ('GOOD', 'Buen estado'), ('FAIR', 'Desgastado')], default='GOOD', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, default='PAL ESPAÑA', max_length=20, null=True)),
                ('platform', models.CharField(blank=True, choices=[('PS1', 'PlayStation 1'), ('PS2', 'PlayStation 2'), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('PSP', 'PlayStation Portable'), ('PSVITA', 'PlayStation Vita'), ('NES', 'Nintendo Entertainment System'), ('SNES', 'Super Nintendo'), ('N64', 'Nintendo 64'), ('GC', 'Nintendo GameCube'), ('WII', 'Nintendo Wii'), ('WIIU', 'Nintendo Wii U'), ('SWITCH', 'Nintendo Switch'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo 3DS'), ('MS', 'Sega Master System'), ('MD', 'Sega Mega Drive'), ('SS', 'Sega Saturn'), ('DC', 'Sega Dreamcast'), ('GG', 'Sega Game Gear'), ('XBOX', 'Xbox Original'), ('X360', 'Xbox 360'), ('XONE', 'Xbox One'), ('XSERIES', 'Xbox Series X/S'), ('ATARI', 'Atari 2600'), ('NEOGEO', 'Neo Geo'), ('PCE', 'PC Engine'), ('GEN', 'Generica / PC')], max_length=20, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missing_components', models.ManyToManyField(blank=True, to='inventory.missingcomponent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('SEALED', 'Precintado'), ('MINT', 'Como nuevo'), ('GOOD', 'Buen estado'), ('FAIR', 'Desgastado')], default='GOOD', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, default='PAL ESPAÑA', max_length=20, null=True)),
                ('platform', models.CharField(blank=True, choices=[('PS1', 'PlayStation 1'), ('PS2', 'PlayStation 2'), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('PSP', 'PlayStation Portable'), ('PSVITA', 'PlayStation Vita'), ('NES', 'Nintendo Entertainment System'), ('SNES', 'Super Nintendo'), ('N64', 'Nintendo 64'), ('GC', 'Nintendo GameCube'), ('WII', 'Nintendo Wii'), ('WIIU', 'Nintendo Wii U'), ('SWITCH', 'Nintendo Switch'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo 3DS'), ('MS', 'Sega Master System'), ('MD', 'Sega Mega Drive'), ('SS', 'Sega Saturn'), ('DC', 'Sega Dreamcast'), ('GG', 'Sega Game Gear'), ('XBOX', 'Xbox Original'), ('X360', 'Xbox 360'), ('XONE', 'Xbox One'), ('XSERIES', 'Xbox Series X/S'), ('ATARI', 'Atari 2600'), ('NEOGEO', 'Neo Geo'), ('PCE', 'PC Engine'), ('GEN', 'Generica / PC')], max_length=20, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missing_components', models.ManyToManyField(blank=True, to='inventory.missingcomponent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('SEALED', 'Precintado'), ('MINT', 'Como nuevo'), ('GOOD', 'Buen estado'), ('FAIR', 'Desgastado')], default='GOOD', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, default='PAL ESPAÑA', max_length=20, null=True)),
                ('platform', models.CharField(blank=True, choices=[('PS1', 'PlayStation 1'), ('PS2', 'PlayStation 2'), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('PSP', 'PlayStation Portable'), ('PSVITA', 'PlayStation Vita'), ('NES', 'Nintendo Entertainment System'), ('SNES', 'Super Nintendo'), ('N64', 'Nintendo 64'), ('GC', 'Nintendo GameCube'), ('WII', 'Nintendo Wii'), ('WIIU', 'Nintendo Wii U'), ('SWITCH', 'Nintendo Switch'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo 3DS'), ('MS', 'Sega Master System'), ('MD', 'Sega Mega Drive'), ('SS', 'Sega Saturn'), ('DC', 'Sega Dreamcast'), ('GG', 'Sega Game Gear'), ('XBOX', 'Xbox Original'), ('X360', 'Xbox 360'), ('XONE', 'Xbox One'), ('XSERIES', 'Xbox Series X/S'), ('ATARI', 'Atari 2600'), ('NEOGEO', 'Neo Geo'), ('PCE', 'PC Engine'), ('GEN', 'Generica / PC')], max_length=20, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missing_components', models.ManyToManyField(blank=True, to='inventory.missingcomponent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
