# Generated by Django 6.0.6 on 2026-06-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='edition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
