# Generated by Django 6.0.6 on 2026-06-30 15:52

import inventory.models.Image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_game_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to=inventory.models.Image.item_image_upload_path, verbose_name='Foto'),
        ),
    ]
