# Generated by Django 6.0.6 on 2026-06-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_itemimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='edition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
