# Generated by Django 6.0.6 on 2026-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_accessory_store_alter_console_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='store',
            field=models.CharField(choices=[('Wallapop', 'Wallapop'), ('Vinted', 'Vinted'), ('Ebay', 'Ebay'), ('Milanuncios', 'Milanuncios'), ('Cash Converters', 'Cash Converters'), ('Game', 'Game'), ('Cex', 'Cex'), ('Amazon', 'Amazon'), ('Fnac', 'Fnac'), ('Carrefour', 'Carrefour'), ('Media Markt', 'Media Markt'), ('El Corte Inglés', 'El Corte Inglés'), ('PcComponentes', 'PcComponentes')], default='Wallapop', max_length=20),
        ),
        migrations.AlterField(
            model_name='console',
            name='store',
            field=models.CharField(choices=[('Wallapop', 'Wallapop'), ('Vinted', 'Vinted'), ('Ebay', 'Ebay'), ('Milanuncios', 'Milanuncios'), ('Cash Converters', 'Cash Converters'), ('Game', 'Game'), ('Cex', 'Cex'), ('Amazon', 'Amazon'), ('Fnac', 'Fnac'), ('Carrefour', 'Carrefour'), ('Media Markt', 'Media Markt'), ('El Corte Inglés', 'El Corte Inglés'), ('PcComponentes', 'PcComponentes')], default='Wallapop', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='store',
            field=models.CharField(choices=[('Wallapop', 'Wallapop'), ('Vinted', 'Vinted'), ('Ebay', 'Ebay'), ('Milanuncios', 'Milanuncios'), ('Cash Converters', 'Cash Converters'), ('Game', 'Game'), ('Cex', 'Cex'), ('Amazon', 'Amazon'), ('Fnac', 'Fnac'), ('Carrefour', 'Carrefour'), ('Media Markt', 'Media Markt'), ('El Corte Inglés', 'El Corte Inglés'), ('PcComponentes', 'PcComponentes')], default='Wallapop', max_length=20),
        ),
    ]
