# Generated by Django 6.0.6 on 2026-09-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_accessory_store_alter_console_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='protective',
            field=models.CharField(choices=[('Sin funda', 'Sin funda'), ('Bolsa plástica', 'Bolsa plástica'), ('Funda PET', 'Funda PET')], default='Sin funda', max_length=20),
        ),
        migrations.AddField(
            model_name='console',
            name='protective',
            field=models.CharField(choices=[('Sin funda', 'Sin funda'), ('Bolsa plástica', 'Bolsa plástica'), ('Funda PET', 'Funda PET')], default='Sin funda', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='protective',
            field=models.CharField(choices=[('Sin funda', 'Sin funda'), ('Bolsa plástica', 'Bolsa plástica'), ('Funda PET', 'Funda PET')], default='Sin funda', max_length=20),
        ),
    ]
