# Generated by Django 6.0.6 on 2026-09-29 19:22

from django.db import migrations, models


def rellenar_total_con_el_precio(apps, schema_editor):
    """
    Rellena `total_price` con el precio del artículo en los registros que ya existían.

    Todos los artículos anteriores a este campo no tienen gastos registrados, así que su total
    es exactamente su precio. Es idempotente: solo toca las filas donde el total está vacío.
    """
    for nombre_modelo in ('Console', 'Game', 'Accessory'):
        modelo = apps.get_model('inventory', nombre_modelo)
        modelo.objects.filter(total_price__isnull=True, price__isnull=False).update(
            total_price=models.F('price'),
        )


def revertir_relleno(apps, schema_editor):
    """Al deshacer, se vacía el total de los registros (el campo se elimina en la misma migración)."""
    for nombre_modelo in ('Console', 'Game', 'Accessory'):
        modelo = apps.get_model('inventory', nombre_modelo)
        modelo.objects.update(total_price=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_accessory_protective_console_protective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio total'),
        ),
        migrations.AddField(
            model_name='console',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio total'),
        ),
        migrations.AddField(
            model_name='game',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio total'),
        ),
        migrations.RunPython(rellenar_total_con_el_precio, revertir_relleno),
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio del artículo'),
        ),
        migrations.AlterField(
            model_name='console',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio del artículo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio del artículo'),
        ),
    ]
