# Generated by Django 6.0.6 on 2026-09-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_accessory_total_price_console_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='purchase_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='enlace de compra'),
        ),
        migrations.AddField(
            model_name='console',
            name='purchase_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='enlace de compra'),
        ),
        migrations.AddField(
            model_name='game',
            name='purchase_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='enlace de compra'),
        ),
    ]
