# Generated by Django 6.0.3 on 2026-03-13 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='fecha de adquisición')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio de compra')),
                ('status', models.CharField(choices=[('SEALED', 'Prencitado'), ('MINT', 'Como nuevo'), ('GOOD', 'Buen estado'), ('FAIR', 'Desgastado')], default='GOOD', max_length=10, verbose_name='estado')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='descripción')),
                ('region', models.CharField(blank=True, default='PAL', max_length=10, null=True, verbose_name='region')),
                ('it_has_a_box', models.BooleanField(default=False, verbose_name='¿tiene caja?')),
                ('complete', models.BooleanField(default=False, verbose_name='¿completo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Añadido el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('plataform', models.CharField(max_length=50, verbose_name='fabricante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='fecha de adquisición')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio de compra')),
                ('status', models.CharField(choices=[('SEALED', 'Prencitado'), ('MINT', 'Como nuevo'), ('GOOD', 'Buen estado'), ('FAIR', 'Desgastado')], default='GOOD', max_length=10, verbose_name='estado')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='descripción')),
                ('region', models.CharField(blank=True, default='PAL', max_length=10, null=True, verbose_name='region')),
                ('it_has_a_box', models.BooleanField(default=False, verbose_name='¿tiene caja?')),
                ('complete', models.BooleanField(default=False, verbose_name='¿completo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Añadido el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('plataform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios_list', to='catalog.console')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='fecha de adquisición')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio de compra')),
                ('status', models.CharField(choices=[('SEALED', 'Prencitado'), ('MINT', 'Como nuevo'), ('GOOD', 'Buen estado'), ('FAIR', 'Desgastado')], default='GOOD', max_length=10, verbose_name='estado')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='descripción')),
                ('region', models.CharField(blank=True, default='PAL', max_length=10, null=True, verbose_name='region')),
                ('it_has_a_box', models.BooleanField(default=False, verbose_name='¿tiene caja?')),
                ('complete', models.BooleanField(default=False, verbose_name='¿completo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Añadido el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('plataform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_list', to='catalog.console')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
