# Generated by Django 6.0.3 on 2026-03-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_accessory_options_alter_console_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='console',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='game',
            name='stock',
        ),
    ]
