# Generated by Django 6.0.3 on 2026-03-16 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='fecha de adquisición')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio de compra')),
                ('status', models.CharField(choices=[('SEALED', 'Prencitado'), ('MINT', 'Como nuevo'), ('GOOD', 'Buen estado'), ('FAIR', 'Desgastado')], default='GOOD', max_length=10, verbose_name='estado')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='descripción')),
                ('region', models.CharField(blank=True, default='PAL', max_length=10, null=True, verbose_name='region')),
                ('plataform', models.CharField(blank=True, choices=[('PS1', 'PlayStation 1'), ('PS2', 'PlayStation 2'), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('PSP', 'PlayStation Portable'), ('PSVITA', 'PlayStation Vita'), ('NES', 'Nintendo Entertainment System'), ('SNES', 'Super Nintendo'), ('N64', 'Nintendo 64'), ('GC', 'Nintendo GameCube'), ('WII', 'Nintendo Wii'), ('WIIU', 'Nintendo Wii U'), ('SWITCH', 'Nintendo Switch'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo 3DS'), ('MS', 'Sega Master System'), ('MD', 'Sega Mega Drive'), ('SS', 'Sega Saturn'), ('DC', 'Sega Dreamcast'), ('GG', 'Sega Game Gear'), ('XBOX', 'Xbox Original'), ('X360', 'Xbox 360'), ('XONE', 'Xbox One'), ('XSERIES', 'Xbox Series X/S'), ('ATARI', 'Atari 2600'), ('NEOGEO', 'Neo Geo'), ('PCE', 'PC Engine'), ('GEN', 'Generica / PC')], max_length=20, null=True)),
                ('complete', models.BooleanField(default=False, verbose_name='¿Completo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Añadido el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MissingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Componente faltante',
                'verbose_name_plural': 'Componentes faltantes',
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.item')),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
            },
            bases=('apps.item',),
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.item')),
            ],
            options={
                'verbose_name': 'Consola',
                'verbose_name_plural': 'Consolas',
            },
            bases=('apps.item',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.item')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
            bases=('apps.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='missing_components',
            field=models.ManyToManyField(blank=True, to='apps.missingcomponent', verbose_name='Falta específicamente:'),
        ),
    ]
