# Generated by Django 6.0.3 on 2026-03-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Accesorio', 'verbose_name_plural': 'Accesorios'},
        ),
        migrations.AlterModelOptions(
            name='console',
            options={'verbose_name': 'Consola', 'verbose_name_plural': 'Consolas'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='gender',
        ),
        migrations.AddField(
            model_name='accessory',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cantidad'),
        ),
        migrations.AddField(
            model_name='console',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cantidad'),
        ),
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='¿Completo?'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='it_has_a_box',
            field=models.BooleanField(default=False, verbose_name='¿Tiene caja?'),
        ),
        migrations.AlterField(
            model_name='console',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='¿Completo?'),
        ),
        migrations.AlterField(
            model_name='console',
            name='it_has_a_box',
            field=models.BooleanField(default=False, verbose_name='¿Tiene caja?'),
        ),
        migrations.AlterField(
            model_name='console',
            name='plataform',
            field=models.CharField(max_length=50, verbose_name='plataforma'),
        ),
        migrations.AlterField(
            model_name='game',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='¿Completo?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='it_has_a_box',
            field=models.BooleanField(default=False, verbose_name='¿Tiene caja?'),
        ),
    ]
