# Generated by Django 6.0.3 on 2026-03-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_accessory_plataforma_console_plataforma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='plataforma',
        ),
        migrations.RemoveField(
            model_name='console',
            name='plataforma',
        ),
        migrations.RemoveField(
            model_name='game',
            name='plataforma',
        ),
        migrations.AlterField(
            model_name='console',
            name='plataform',
            field=models.CharField(blank=True, choices=[('PS1', 'PlayStation 1'), ('PS2', 'PlayStation 2'), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('PSP', 'PlayStation Portable'), ('PSVITA', 'PlayStation Vita'), ('NES', 'Nintendo Entertainment System'), ('SNES', 'Super Nintendo'), ('N64', 'Nintendo 64'), ('GC', 'Nintendo GameCube'), ('WII', 'Nintendo Wii'), ('WIIU', 'Nintendo Wii U'), ('SWITCH', 'Nintendo Switch'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo 3DS'), ('MS', 'Sega Master System'), ('MD', 'Sega Mega Drive'), ('SS', 'Sega Saturn'), ('DC', 'Sega Dreamcast'), ('GG', 'Sega Game Gear'), ('XBOX', 'Xbox Original'), ('X360', 'Xbox 360'), ('XONE', 'Xbox One'), ('XSERIES', 'Xbox Series X/S'), ('ATARI', 'Atari 2600'), ('NEOGEO', 'Neo Geo'), ('PCE', 'PC Engine'), ('GEN', 'Generica / PC')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='plataform',
            field=models.CharField(blank=True, choices=[('PS1', 'PlayStation 1'), ('PS2', 'PlayStation 2'), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('PSP', 'PlayStation Portable'), ('PSVITA', 'PlayStation Vita'), ('NES', 'Nintendo Entertainment System'), ('SNES', 'Super Nintendo'), ('N64', 'Nintendo 64'), ('GC', 'Nintendo GameCube'), ('WII', 'Nintendo Wii'), ('WIIU', 'Nintendo Wii U'), ('SWITCH', 'Nintendo Switch'), ('GB', 'Game Boy'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('DS', 'Nintendo DS'), ('3DS', 'Nintendo 3DS'), ('MS', 'Sega Master System'), ('MD', 'Sega Mega Drive'), ('SS', 'Sega Saturn'), ('DC', 'Sega Dreamcast'), ('GG', 'Sega Game Gear'), ('XBOX', 'Xbox Original'), ('X360', 'Xbox 360'), ('XONE', 'Xbox One'), ('XSERIES', 'Xbox Series X/S'), ('ATARI', 'Atari 2600'), ('NEOGEO', 'Neo Geo'), ('PCE', 'PC Engine'), ('GEN', 'Generica / PC')], max_length=20, null=True),
        ),
    ]
